### PR TITLE
Huge changes

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Rename `PHPImageConverter`  to `ImageConverter` class.
- Using the `PHPUnit` to do unit tests.
- Composer package ready.
- Let this package require `php-7.1` version at least.
- Using the Travis CI build. The build log is available [here](https://travis-ci.org/peter279k/php-image-converter/builds/525606089).
- Using `php-coveralls` to integrate the coveralls code coverage service. The code coverage report is [here](https://coveralls.io/github/peter279k/php-image-converter).
- Remove the `to` folder because it's the output folder.
- It's related to issue #1.

### CODE REVIEW

**Comment by jenstornell** [comment]
@peter279k You call that "minor changes"? You have rewritten almost the whole thing. =)

Most of it looks good (without testing it), but I have a few questions about it.

- https://github.com/jenstornell/php-image-converter/pull/3/commits/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR17 What is the reason for using constants here?
- https://github.com/jenstornell/php-image-converter/pull/3/commits/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR115 Why a function to check for webp?
- https://github.com/jenstornell/php-image-converter/pull/3/commits/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR83 Why check for not webp here?

Thanks!

**Comment by peter279k** [comment]
> @peter279k You call that "minor changes"? You have rewritten almost the whole thing. =)
> 
> Most of it looks good (without testing it), but I have a few questions about it.
> 
> * [71fd16b#diff-81ded2d72b04cce6321fad9e0f6c9e3cR17](https://github.com/jenstornell/php-image-converter/commit/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR17) What is the reason for using constants here?
> * [71fd16b#diff-81ded2d72b04cce6321fad9e0f6c9e3cR115](https://github.com/jenstornell/php-image-converter/commit/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR115) Why a function to check for webp?
> * [71fd16b#diff-81ded2d72b04cce6321fad9e0f6c9e3cR83](https://github.com/jenstornell/php-image-converter/commit/71fd16b8f5e923cfc31425244d3974d39ba43ceb#diff-81ded2d72b04cce6321fad9e0f6c9e3cR83) Why check for not webp here?

- What is the reason for using constants here?

This const value lists are for the `exif_imagetype` and this can check the image contents to determine the current image formats :).

- Why a function to check for webp?

Actually, the `webp` image format cannot be recognized via `exif_imagetype` correctly if we use the `php-5.6` version.

If we let package require `php-7.1` version at least, this `webp` check method can be removed.

- Why check for not webp here?

As the previous answer, if we let package require the `php-7.1` version at least, this not webp condtion can be removed.

**Comment by peter279k** [comment]
@jenstornell, thank you for your reply.

I name the wrong title, and I will rename original to `Huge changes`.

I hope you can review them in details at your available time :).

**Comment by jenstornell** [comment]
@peter279k I will test it when I have more time.

PHP 7.1 was released december 2016 and I think it can be a requirement. It makes the code shorter and also a bit more readable because of that.

**Comment by peter279k** [comment]
Hi @jenstornell, thank you for your reply.

I've removed the `isWebpImage`  method because the package requires `php-7.1` version at least.

**Pull request merged**
