### PR TITLE
Add contribution guide

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Add contribution guide.

### CODE REVIEW

**Comment by jenstornell** [comment]
I'm not really sure about this one. I do think it's good to have some information to people who may contribute, but I think a better way would be these two.

- Add multiple issue templates, one for new features and one for new issues. Maybe even one for questions as well. https://help.github.com/en/articles/creating-issue-templates-for-your-repository
- Try to shrink your guide and then add it as a section in the `readme.md` file instead.

What do you think?

**Comment by peter279k** [comment]
Hi @jenstornell, thank you for your reply.

- I think we can add the issue template and mention that in `contributing` file.
- Add the `contributing` fie is important and we can add a section to refer this `contributing` guide link.

**Review by jenstornell — APPROVED** [review]
Well written, but quite long. I don't think most contributors will not read half of it. But I guess it's good to have a document like this to fall back on to.

**Comment by peter279k** [comment]
Hi @jenstornell, thank you for your reply.

I've added the `contributing.md` in `Contributing` section.

I think it's time to be merged.

**Pull request merged**
